# Generated by Django 4.2.5 on 2024-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "Пользователь с таким email уже существует"},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
