# Generated by Django 4.2.5 on 2024-02-11 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_alter_basket_book_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="liked_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
