# Generated by Django 4.2.5 on 2023-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_first_name_order_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="expired",
            new_name="archived",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "На рассмотрении"),
                    (1, "Готов к выдаче"),
                    (2, "На выдаче"),
                    (3, "Возвращено"),
                    (4, "Просрочено"),
                    (5, "Отменен"),
                ],
                default=0,
            ),
        ),
    ]
